### ISSUE TITLE
Formula for magnitude:

### ISSUE THREAD

**Issue by bmarzban** [actigraph/agcounts#12]
Hi Ali, thanks for the great package!
I have tried to run the test/demo code, but I had one issue and one important question?

- The issue was I had to comment out the following line to run the test in the get_counts_csv :
 # ts = ts[0:counts.shape[0]]

- The question is,   calculating the magnitude of the count vector, I think ^ does a binary xor operation and not a power operation, is that what it meant to do here?  cause it affects the outputs. 

  counts["AC"] = (counts["Axis1"]^2 + counts["Axis2"]^2 + counts["Axis3"]^2) ** 0.5

Your response and feedback is highly appreciated. Thanks!

**Comment by bmarzban** [comment]
![after ](https://user-images.githubusercontent.com/49318539/190268096-5ad9b8e2-0e61-4369-bc7d-1691370478a1.png)
![before](https://user-images.githubusercontent.com/49318539/190268122-44623567-d545-4834-8525-42dfa574de88.png)

FYI, Here I plotted the change in counts before and after changing the operator:    ^ to ** 

Thanks.

**Comment by rouzbeh** [comment]
Thank you very much. I have created a pull request to fix this.
