### ISSUE TITLE
Low frequency extension (LFE) 

### ISSUE THREAD

**Issue by yananlong** [actigraph/agcounts#23]
The LFE, according to the [Actigraph documentation](https://actigraphcorp.my.site.com/support/s/article/Low-Frequency-Extension-Explained), reduces the threshold of acceleration level for the recorded activity to be considered human movement. In `_trim_data`, the [code to perform the LFE](https://github.com/actigraph/agcounts/blob/main/agcounts/extract.py#L158-L168) is located in L158-168. However, this line (L163)

`
trim_data[(trim_data < min_count) & (trim_data >= 4)] = 0
`

does not seem to make any modification to the `trim_data` array since it's not possible for a value to be both $< 1$ and $\geqslant 4.$

Should it have read `trim_data[(trim_data < min_count)] = 0` (i.e. setting values $< 1$ to $0$) instead?

**Comment by rouzbeh** [comment]
Thanks for reporting this. The original code for this was 

```
if lfe_select:
  min_count = 1
  max_count = 128 * 1

  for i in range(len(bpf_data[0])):
    if abs(bpf_data[0, i]) > max_count:
        trim_data[0, i] = max_count
    elif abs(bpf_data[0, i]) < min_count:
        trim_data[0, i] = 0
    elif abs(bpf_data[0, i]) < 4:
        trim_data[0, i] = np.floor(abs(bpf_data[0, i])) - 1
    else:
        trim_data[0, i] = np.floor(abs(bpf_data[0, i]))  # floor
```
Which got translated into the current code. I agree that with the hard-coded values, this doesn't make any sense anymore. I'll look into fixing it.
