### ISSUE TITLE
Support: NumPy 2.0

### ISSUE THREAD

**Issue by josefheidler** [actigraph/agcounts#28]
Hey,

would it be possible to support NumPy 2.0?

```
AttributeError: `np.float_` was removed in the NumPy 2.0 release. Use `np.float64` instead.
```

P.S.: Thanks for Python 3.12

**Comment by rouzbeh** [comment]
Sure, can you please let me know where this happens?

**Comment by josefheidler** [comment]
I can see that you have already figured it out. Thanks. :)
